version: "3.7"

services:
  web:
    build: .
    command: python /EEnergy_backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/EEnergy_backend
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db

  db:
    image: postgres:12
    ports:
      - 5432
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
